# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/my-manager.v2/ui/dialog_robot_run.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_RobotRun(object):
    def setupUi(self, Dialog_RobotRun):
        Dialog_RobotRun.setObjectName("Dialog_RobotRun")
        Dialog_RobotRun.resize(480, 111)
        Dialog_RobotRun.setStyleSheet("#Dialog_RobotRun{\n"
"  font-family: \"Courier New\";\n"
"  background-color: #FFFFFF;\n"
"  font-size: 12px;\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 12px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"  font-size: 12px;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"  font-size: 12px;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 12px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 12px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 12px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"  font-size: 12px;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Dialog_RobotRun)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setObjectName("gridLayout")
        self.dialog_robot_run_layout = QtWidgets.QGridLayout()
        self.dialog_robot_run_layout.setContentsMargins(0, -1, -1, 0)
        self.dialog_robot_run_layout.setHorizontalSpacing(0)
        self.dialog_robot_run_layout.setVerticalSpacing(4)
        self.dialog_robot_run_layout.setObjectName("dialog_robot_run_layout")
        self.group_num_container = QtWidgets.QGroupBox(parent=Dialog_RobotRun)
        self.group_num_container.setTitle("")
        self.group_num_container.setObjectName("group_num_container")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.group_num_container)
        self.verticalLayout_26.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_26.setSpacing(4)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.group_num_layout = QtWidgets.QVBoxLayout()
        self.group_num_layout.setSpacing(0)
        self.group_num_layout.setObjectName("group_num_layout")
        self.group_num_label = QtWidgets.QLabel(parent=self.group_num_container)
        self.group_num_label.setStyleSheet("font-size: 10px")
        self.group_num_label.setObjectName("group_num_label")
        self.group_num_layout.addWidget(self.group_num_label)
        self.group_num_input = QtWidgets.QLineEdit(parent=self.group_num_container)
        self.group_num_input.setInputMask("")
        self.group_num_input.setObjectName("group_num_input")
        self.group_num_layout.addWidget(self.group_num_input)
        self.verticalLayout_26.addLayout(self.group_num_layout)
        self.dialog_robot_run_layout.addWidget(self.group_num_container, 0, 2, 1, 1)
        self.thread_num_container = QtWidgets.QGroupBox(parent=Dialog_RobotRun)
        self.thread_num_container.setTitle("")
        self.thread_num_container.setObjectName("thread_num_container")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.thread_num_container)
        self.verticalLayout_25.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_25.setSpacing(4)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.thread_num_layout = QtWidgets.QVBoxLayout()
        self.thread_num_layout.setSpacing(0)
        self.thread_num_layout.setObjectName("thread_num_layout")
        self.thread_num_label = QtWidgets.QLabel(parent=self.thread_num_container)
        self.thread_num_label.setStyleSheet("font-size: 10px")
        self.thread_num_label.setObjectName("thread_num_label")
        self.thread_num_layout.addWidget(self.thread_num_label)
        self.thread_num_input = QtWidgets.QLineEdit(parent=self.thread_num_container)
        self.thread_num_input.setInputMask("")
        self.thread_num_input.setObjectName("thread_num_input")
        self.thread_num_layout.addWidget(self.thread_num_input)
        self.verticalLayout_25.addLayout(self.thread_num_layout)
        self.dialog_robot_run_layout.addWidget(self.thread_num_container, 0, 1, 1, 1)
        self.delay_time_container = QtWidgets.QGroupBox(parent=Dialog_RobotRun)
        self.delay_time_container.setTitle("")
        self.delay_time_container.setObjectName("delay_time_container")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.delay_time_container)
        self.verticalLayout_29.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_29.setSpacing(4)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.delay_time_layout = QtWidgets.QVBoxLayout()
        self.delay_time_layout.setSpacing(0)
        self.delay_time_layout.setObjectName("delay_time_layout")
        self.delay_time_label = QtWidgets.QLabel(parent=self.delay_time_container)
        self.delay_time_label.setStyleSheet("font-size: 10px")
        self.delay_time_label.setObjectName("delay_time_label")
        self.delay_time_layout.addWidget(self.delay_time_label)
        self.delay_time_input = QtWidgets.QLineEdit(parent=self.delay_time_container)
        self.delay_time_input.setInputMask("")
        self.delay_time_input.setObjectName("delay_time_input")
        self.delay_time_layout.addWidget(self.delay_time_input)
        self.verticalLayout_29.addLayout(self.delay_time_layout)
        self.dialog_robot_run_layout.addWidget(self.delay_time_container, 0, 3, 1, 1)
        self.ai_container = QtWidgets.QGroupBox(parent=Dialog_RobotRun)
        self.ai_container.setTitle("")
        self.ai_container.setObjectName("ai_container")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.ai_container)
        self.verticalLayout_30.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_30.setSpacing(4)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.ai_container_layout = QtWidgets.QVBoxLayout()
        self.ai_container_layout.setSpacing(0)
        self.ai_container_layout.setObjectName("ai_container_layout")
        self.is_rewrite_by_ai = QtWidgets.QCheckBox(parent=self.ai_container)
        self.is_rewrite_by_ai.setObjectName("is_rewrite_by_ai")
        self.ai_container_layout.addWidget(self.is_rewrite_by_ai)
        self.verticalLayout_30.addLayout(self.ai_container_layout)
        self.dialog_robot_run_layout.addWidget(self.ai_container, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.dialog_robot_run_layout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_RobotRun)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog_RobotRun)
        self.buttonBox.accepted.connect(Dialog_RobotRun.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_RobotRun.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_RobotRun)
        Dialog_RobotRun.setTabOrder(self.thread_num_input, self.group_num_input)
        Dialog_RobotRun.setTabOrder(self.group_num_input, self.delay_time_input)

    def retranslateUi(self, Dialog_RobotRun):
        _translate = QtCore.QCoreApplication.translate
        Dialog_RobotRun.setWindowTitle(_translate("Dialog_RobotRun", "Dialog"))
        self.group_num_label.setText(_translate("Dialog_RobotRun", "Số lượng nhóm (discussion)"))
        self.group_num_input.setText(_translate("Dialog_RobotRun", "5"))
        self.thread_num_label.setText(_translate("Dialog_RobotRun", "Số lượng thread"))
        self.thread_num_input.setText(_translate("Dialog_RobotRun", "1"))
        self.delay_time_label.setText(_translate("Dialog_RobotRun", "Thời gian delay (phút)"))
        self.delay_time_input.setText(_translate("Dialog_RobotRun", "3"))
        self.is_rewrite_by_ai.setText(_translate("Dialog_RobotRun", "Rewrite by AI"))
