# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/my-manager.v2/ui/dialog_profile.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Profile(object):
    def setupUi(self, Dialog_Profile):
        Dialog_Profile.setObjectName("Dialog_Profile")
        Dialog_Profile.resize(718, 344)
        Dialog_Profile.setStyleSheet("#Dialog_Profile {\n"
"  font-family: \"Courier New\";\n"
"  background-color: #FFFFFF;\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"}\n"
"\n"
"QCheckBox{\n"
"  color: #212529;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Profile)
        self.verticalLayout.setObjectName("verticalLayout")
        self.section_1_layout = QtWidgets.QHBoxLayout()
        self.section_1_layout.setObjectName("section_1_layout")
        self.uid_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.uid_container.setTitle("")
        self.uid_container.setObjectName("uid_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.uid_container)
        self.verticalLayout_2.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uid_container_layout = QtWidgets.QVBoxLayout()
        self.uid_container_layout.setSpacing(0)
        self.uid_container_layout.setObjectName("uid_container_layout")
        self.uid_label = QtWidgets.QLabel(parent=self.uid_container)
        self.uid_label.setStyleSheet("font-size: 10px")
        self.uid_label.setObjectName("uid_label")
        self.uid_container_layout.addWidget(self.uid_label)
        self.uid_input = QtWidgets.QLineEdit(parent=self.uid_container)
        self.uid_input.setObjectName("uid_input")
        self.uid_container_layout.addWidget(self.uid_input)
        self.verticalLayout_2.addLayout(self.uid_container_layout)
        self.section_1_layout.addWidget(self.uid_container)
        self.username_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.username_container.setTitle("")
        self.username_container.setObjectName("username_container")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.username_container)
        self.verticalLayout_23.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.username_container_layout = QtWidgets.QVBoxLayout()
        self.username_container_layout.setSpacing(0)
        self.username_container_layout.setObjectName("username_container_layout")
        self.username_label = QtWidgets.QLabel(parent=self.username_container)
        self.username_label.setStyleSheet("font-size: 10px")
        self.username_label.setObjectName("username_label")
        self.username_container_layout.addWidget(self.username_label)
        self.username_input = QtWidgets.QLineEdit(parent=self.username_container)
        self.username_input.setObjectName("username_input")
        self.username_container_layout.addWidget(self.username_input)
        self.verticalLayout_23.addLayout(self.username_container_layout)
        self.section_1_layout.addWidget(self.username_container)
        self.status_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.status_container.setTitle("")
        self.status_container.setObjectName("status_container")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.status_container)
        self.verticalLayout_21.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.status_container_layout = QtWidgets.QVBoxLayout()
        self.status_container_layout.setSpacing(0)
        self.status_container_layout.setObjectName("status_container_layout")
        self.status_checkbox = QtWidgets.QCheckBox(parent=self.status_container)
        self.status_checkbox.setChecked(True)
        self.status_checkbox.setObjectName("status_checkbox")
        self.status_container_layout.addWidget(self.status_checkbox)
        self.verticalLayout_21.addLayout(self.status_container_layout)
        self.section_1_layout.addWidget(self.status_container)
        self.verticalLayout.addLayout(self.section_1_layout)
        self.section_2_layout = QtWidgets.QHBoxLayout()
        self.section_2_layout.setObjectName("section_2_layout")
        self.password_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.password_container.setTitle("")
        self.password_container.setObjectName("password_container")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.password_container)
        self.verticalLayout_6.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.password_container_layout = QtWidgets.QVBoxLayout()
        self.password_container_layout.setSpacing(0)
        self.password_container_layout.setObjectName("password_container_layout")
        self.password_label = QtWidgets.QLabel(parent=self.password_container)
        self.password_label.setStyleSheet("font-size: 10px")
        self.password_label.setObjectName("password_label")
        self.password_container_layout.addWidget(self.password_label)
        self.password_input = QtWidgets.QLineEdit(parent=self.password_container)
        self.password_input.setObjectName("password_input")
        self.password_container_layout.addWidget(self.password_input)
        self.verticalLayout_6.addLayout(self.password_container_layout)
        self.section_2_layout.addWidget(self.password_container)
        self.two_fa_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.two_fa_container.setTitle("")
        self.two_fa_container.setObjectName("two_fa_container")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.two_fa_container)
        self.verticalLayout_9.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.two_fa_container_layout = QtWidgets.QVBoxLayout()
        self.two_fa_container_layout.setSpacing(0)
        self.two_fa_container_layout.setObjectName("two_fa_container_layout")
        self.two_fa_label = QtWidgets.QLabel(parent=self.two_fa_container)
        self.two_fa_label.setStyleSheet("font-size: 10px")
        self.two_fa_label.setObjectName("two_fa_label")
        self.two_fa_container_layout.addWidget(self.two_fa_label)
        self.two_fa_input = QtWidgets.QLineEdit(parent=self.two_fa_container)
        self.two_fa_input.setObjectName("two_fa_input")
        self.two_fa_container_layout.addWidget(self.two_fa_input)
        self.verticalLayout_9.addLayout(self.two_fa_container_layout)
        self.section_2_layout.addWidget(self.two_fa_container)
        self.verticalLayout.addLayout(self.section_2_layout)
        self.section_3_layout = QtWidgets.QHBoxLayout()
        self.section_3_layout.setObjectName("section_3_layout")
        self.phone_number_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.phone_number_container.setTitle("")
        self.phone_number_container.setObjectName("phone_number_container")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.phone_number_container)
        self.verticalLayout_14.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.phone_number_container_layout = QtWidgets.QVBoxLayout()
        self.phone_number_container_layout.setSpacing(0)
        self.phone_number_container_layout.setObjectName("phone_number_container_layout")
        self.phone_number_label = QtWidgets.QLabel(parent=self.phone_number_container)
        self.phone_number_label.setStyleSheet("font-size: 10px")
        self.phone_number_label.setObjectName("phone_number_label")
        self.phone_number_container_layout.addWidget(self.phone_number_label)
        self.phone_number_input = QtWidgets.QLineEdit(parent=self.phone_number_container)
        self.phone_number_input.setObjectName("phone_number_input")
        self.phone_number_container_layout.addWidget(self.phone_number_input)
        self.verticalLayout_14.addLayout(self.phone_number_container_layout)
        self.section_3_layout.addWidget(self.phone_number_container)
        self.email_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.email_container.setTitle("")
        self.email_container.setObjectName("email_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.email_container)
        self.verticalLayout_5.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.email_container_layout = QtWidgets.QVBoxLayout()
        self.email_container_layout.setSpacing(0)
        self.email_container_layout.setObjectName("email_container_layout")
        self.email_label = QtWidgets.QLabel(parent=self.email_container)
        self.email_label.setStyleSheet("font-size: 10px")
        self.email_label.setObjectName("email_label")
        self.email_container_layout.addWidget(self.email_label)
        self.email_input = QtWidgets.QLineEdit(parent=self.email_container)
        self.email_input.setObjectName("email_input")
        self.email_container_layout.addWidget(self.email_input)
        self.verticalLayout_5.addLayout(self.email_container_layout)
        self.section_3_layout.addWidget(self.email_container)
        self.email_password_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.email_password_container.setTitle("")
        self.email_password_container.setObjectName("email_password_container")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.email_password_container)
        self.verticalLayout_17.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.email_password_container_layout = QtWidgets.QVBoxLayout()
        self.email_password_container_layout.setSpacing(0)
        self.email_password_container_layout.setObjectName("email_password_container_layout")
        self.email_password_label = QtWidgets.QLabel(parent=self.email_password_container)
        self.email_password_label.setStyleSheet("font-size: 10px")
        self.email_password_label.setObjectName("email_password_label")
        self.email_password_container_layout.addWidget(self.email_password_label)
        self.email_password_input = QtWidgets.QLineEdit(parent=self.email_password_container)
        self.email_password_input.setObjectName("email_password_input")
        self.email_password_container_layout.addWidget(self.email_password_input)
        self.verticalLayout_17.addLayout(self.email_password_container_layout)
        self.section_3_layout.addWidget(self.email_password_container)
        self.verticalLayout.addLayout(self.section_3_layout)
        self.section_4_layout = QtWidgets.QHBoxLayout()
        self.section_4_layout.setObjectName("section_4_layout")
        self.note_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.note_container.setTitle("")
        self.note_container.setObjectName("note_container")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.note_container)
        self.verticalLayout_30.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.note_container_layout = QtWidgets.QVBoxLayout()
        self.note_container_layout.setSpacing(0)
        self.note_container_layout.setObjectName("note_container_layout")
        self.note_label = QtWidgets.QLabel(parent=self.note_container)
        self.note_label.setStyleSheet("font-size: 10px")
        self.note_label.setObjectName("note_label")
        self.note_container_layout.addWidget(self.note_label)
        self.note_input = QtWidgets.QLineEdit(parent=self.note_container)
        self.note_input.setObjectName("note_input")
        self.note_container_layout.addWidget(self.note_input)
        self.verticalLayout_30.addLayout(self.note_container_layout)
        self.section_4_layout.addWidget(self.note_container)
        self.type_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.type_container.setTitle("")
        self.type_container.setObjectName("type_container")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.type_container)
        self.verticalLayout_25.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.type_container_layout = QtWidgets.QVBoxLayout()
        self.type_container_layout.setSpacing(0)
        self.type_container_layout.setObjectName("type_container_layout")
        self.type_label = QtWidgets.QLabel(parent=self.type_container)
        self.type_label.setStyleSheet("font-size: 10px")
        self.type_label.setObjectName("type_label")
        self.type_container_layout.addWidget(self.type_label)
        self.type_input = QtWidgets.QLineEdit(parent=self.type_container)
        self.type_input.setObjectName("type_input")
        self.type_container_layout.addWidget(self.type_input)
        self.verticalLayout_25.addLayout(self.type_container_layout)
        self.section_4_layout.addWidget(self.type_container)
        self.group_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.group_container.setTitle("")
        self.group_container.setObjectName("group_container")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.group_container)
        self.verticalLayout_13.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.group_container_layout = QtWidgets.QVBoxLayout()
        self.group_container_layout.setSpacing(0)
        self.group_container_layout.setObjectName("group_container_layout")
        self.group_label = QtWidgets.QLabel(parent=self.group_container)
        self.group_label.setStyleSheet("font-size: 10px")
        self.group_label.setObjectName("group_label")
        self.group_container_layout.addWidget(self.group_label)
        self.group_input = QtWidgets.QLineEdit(parent=self.group_container)
        self.group_input.setObjectName("group_input")
        self.group_container_layout.addWidget(self.group_input)
        self.verticalLayout_13.addLayout(self.group_container_layout)
        self.section_4_layout.addWidget(self.group_container)
        self.name_container = QtWidgets.QGroupBox(parent=Dialog_Profile)
        self.name_container.setTitle("")
        self.name_container.setObjectName("name_container")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.name_container)
        self.verticalLayout_33.setContentsMargins(4, 8, 8, 4)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.name_container_layout = QtWidgets.QVBoxLayout()
        self.name_container_layout.setSpacing(0)
        self.name_container_layout.setObjectName("name_container_layout")
        self.name_label = QtWidgets.QLabel(parent=self.name_container)
        self.name_label.setStyleSheet("font-size: 10px")
        self.name_label.setObjectName("name_label")
        self.name_container_layout.addWidget(self.name_label)
        self.name_combobox = QtWidgets.QComboBox(parent=self.name_container)
        self.name_combobox.setObjectName("name_combobox")
        self.name_container_layout.addWidget(self.name_combobox)
        self.verticalLayout_33.addLayout(self.name_container_layout)
        self.section_4_layout.addWidget(self.name_container)
        self.verticalLayout.addLayout(self.section_4_layout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_Profile)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Profile)
        self.buttonBox.accepted.connect(Dialog_Profile.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Profile.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Profile)

    def retranslateUi(self, Dialog_Profile):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Profile.setWindowTitle(_translate("Dialog_Profile", "Dialog"))
        self.uid_label.setText(_translate("Dialog_Profile", "UID"))
        self.username_label.setText(_translate("Dialog_Profile", "Username"))
        self.status_checkbox.setText(_translate("Dialog_Profile", "Is live"))
        self.password_label.setText(_translate("Dialog_Profile", "Passowrd"))
        self.two_fa_label.setText(_translate("Dialog_Profile", "2FA"))
        self.phone_number_label.setText(_translate("Dialog_Profile", "Phone number"))
        self.email_label.setText(_translate("Dialog_Profile", "email"))
        self.email_password_label.setText(_translate("Dialog_Profile", "Email password"))
        self.note_label.setText(_translate("Dialog_Profile", "Note"))
        self.type_label.setText(_translate("Dialog_Profile", "Type"))
        self.group_label.setText(_translate("Dialog_Profile", "Group"))
        self.name_label.setText(_translate("Dialog_Profile", "Name"))
