# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/my-manager.v2/ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 600))
        MainWindow.setStyleSheet("QRadioButton {\n"
"    padding: 10px; \n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"/* Ẩn indicator mặc định */\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"QRadioButton:!checked {\n"
"}\n"
"QRadioButton:checked {\n"
"    border-color: blue;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidebar_container.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sidebar_container.setObjectName("sidebar_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.real_estate = QtWidgets.QRadioButton(parent=self.sidebar_container)
        self.real_estate.setIconSize(QtCore.QSize(24, 16))
        self.real_estate.setObjectName("real_estate")
        self.verticalLayout.addWidget(self.real_estate)
        self.misc = QtWidgets.QRadioButton(parent=self.sidebar_container)
        self.misc.setIconSize(QtCore.QSize(16, 16))
        self.misc.setObjectName("misc")
        self.verticalLayout.addWidget(self.misc)
        self.profile = QtWidgets.QRadioButton(parent=self.sidebar_container)
        self.profile.setObjectName("profile")
        self.verticalLayout.addWidget(self.profile)
        self.robot = QtWidgets.QRadioButton(parent=self.sidebar_container)
        self.robot.setObjectName("robot")
        self.verticalLayout.addWidget(self.robot)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.template = QtWidgets.QRadioButton(parent=self.sidebar_container)
        self.template.setObjectName("template")
        self.verticalLayout.addWidget(self.template)
        self.setting = QtWidgets.QRadioButton(parent=self.sidebar_container)
        self.setting.setObjectName("setting")
        self.verticalLayout.addWidget(self.setting)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.sidebar_container)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.content_container = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.content_container.setObjectName("content_container")
        self.horizontalLayout.addWidget(self.content_container)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.status_bar = QtWidgets.QStatusBar(parent=MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.real_estate.setText(_translate("MainWindow", "Properties"))
        self.misc.setText(_translate("MainWindow", "Miscs"))
        self.profile.setText(_translate("MainWindow", "Profiles"))
        self.robot.setText(_translate("MainWindow", "Robot"))
        self.template.setText(_translate("MainWindow", "Templates"))
        self.setting.setText(_translate("MainWindow", "Settings"))
