# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/my-manager.v2/ui/page_robot.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PageFacebookRobot(object):
    def setupUi(self, PageFacebookRobot):
        PageFacebookRobot.setObjectName("PageFacebookRobot")
        PageFacebookRobot.resize(981, 640)
        PageFacebookRobot.setStyleSheet("#PageFacebookRobot{\n"
"  font-family: \"Courier New\";\n"
"  background-color: #FFFFFF;\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"}\n"
"\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(PageFacebookRobot)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.container_layout = QtWidgets.QHBoxLayout()
        self.container_layout.setContentsMargins(-1, -1, 0, -1)
        self.container_layout.setObjectName("container_layout")
        self.display_container = QtWidgets.QVBoxLayout()
        self.display_container.setSpacing(4)
        self.display_container.setObjectName("display_container")
        self.search_container = QtWidgets.QWidget(parent=PageFacebookRobot)
        self.search_container.setObjectName("search_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.search_container)
        self.horizontalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setContentsMargins(0, 0, 0, 0)
        self.search_layout.setSpacing(4)
        self.search_layout.setObjectName("search_layout")
        self.uid_container = QtWidgets.QGroupBox(parent=self.search_container)
        self.uid_container.setObjectName("uid_container")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.uid_container)
        self.verticalLayout_22.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_22.setSpacing(4)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.uid_input = QtWidgets.QLineEdit(parent=self.uid_container)
        self.uid_input.setObjectName("uid_input")
        self.verticalLayout_22.addWidget(self.uid_input)
        self.search_layout.addWidget(self.uid_container)
        self.username_container = QtWidgets.QGroupBox(parent=self.search_container)
        self.username_container.setObjectName("username_container")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.username_container)
        self.verticalLayout_24.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_24.setSpacing(4)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.username_input = QtWidgets.QLineEdit(parent=self.username_container)
        self.username_input.setObjectName("username_input")
        self.verticalLayout_24.addWidget(self.username_input)
        self.search_layout.addWidget(self.username_container)
        self.note_container = QtWidgets.QGroupBox(parent=self.search_container)
        self.note_container.setObjectName("note_container")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.note_container)
        self.verticalLayout_25.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_25.setSpacing(4)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.note_input = QtWidgets.QLineEdit(parent=self.note_container)
        self.note_input.setObjectName("note_input")
        self.verticalLayout_25.addWidget(self.note_input)
        self.search_layout.addWidget(self.note_container)
        self.type_container = QtWidgets.QGroupBox(parent=self.search_container)
        self.type_container.setObjectName("type_container")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.type_container)
        self.verticalLayout_26.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_26.setSpacing(4)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.type_input = QtWidgets.QLineEdit(parent=self.type_container)
        self.type_input.setObjectName("type_input")
        self.verticalLayout_26.addWidget(self.type_input)
        self.search_layout.addWidget(self.type_container)
        self.groupt_container = QtWidgets.QGroupBox(parent=self.search_container)
        self.groupt_container.setObjectName("groupt_container")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.groupt_container)
        self.verticalLayout_27.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_27.setSpacing(4)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.group_input = QtWidgets.QLineEdit(parent=self.groupt_container)
        self.group_input.setObjectName("group_input")
        self.verticalLayout_27.addWidget(self.group_input)
        self.search_layout.addWidget(self.groupt_container)
        self.name_container = QtWidgets.QGroupBox(parent=self.search_container)
        self.name_container.setObjectName("name_container")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.name_container)
        self.verticalLayout_28.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_28.setSpacing(4)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.name_input = QtWidgets.QLineEdit(parent=self.name_container)
        self.name_input.setObjectName("name_input")
        self.verticalLayout_28.addWidget(self.name_input)
        self.search_layout.addWidget(self.name_container)
        self.filter_container_2 = QtWidgets.QGroupBox(parent=self.search_container)
        self.filter_container_2.setObjectName("filter_container_2")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.filter_container_2)
        self.verticalLayout_29.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_29.setSpacing(4)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.filter_input = QtWidgets.QLineEdit(parent=self.filter_container_2)
        self.filter_input.setObjectName("filter_input")
        self.verticalLayout_29.addWidget(self.filter_input)
        self.search_layout.addWidget(self.filter_container_2)
        self.horizontalLayout_6.addLayout(self.search_layout)
        self.display_container.addWidget(self.search_container)
        self.robot_table_container = QtWidgets.QWidget(parent=PageFacebookRobot)
        self.robot_table_container.setObjectName("robot_table_container")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.robot_table_container)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.robot_table_container_layout = QtWidgets.QHBoxLayout()
        self.robot_table_container_layout.setObjectName("robot_table_container_layout")
        self.profiles_table = QtWidgets.QTableView(parent=self.robot_table_container)
        self.profiles_table.setObjectName("profiles_table")
        self.robot_table_container_layout.addWidget(self.profiles_table)
        self.actions_tree_view = QtWidgets.QTreeWidget(parent=self.robot_table_container)
        self.actions_tree_view.setObjectName("actions_tree_view")
        self.actions_tree_view.headerItem().setText(0, "1")
        self.robot_table_container_layout.addWidget(self.actions_tree_view)
        self.horizontalLayout_8.addLayout(self.robot_table_container_layout)
        self.display_container.addWidget(self.robot_table_container)
        self.container_layout.addLayout(self.display_container)
        self.actions_container = QtWidgets.QWidget(parent=PageFacebookRobot)
        self.actions_container.setMinimumSize(QtCore.QSize(300, 0))
        self.actions_container.setObjectName("actions_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.actions_container)
        self.verticalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.actions_container_layout = QtWidgets.QVBoxLayout()
        self.actions_container_layout.setContentsMargins(-1, -1, -1, 0)
        self.actions_container_layout.setSpacing(4)
        self.actions_container_layout.setObjectName("actions_container_layout")
        self.action_payload_layout = QtWidgets.QVBoxLayout()
        self.action_payload_layout.setObjectName("action_payload_layout")
        self.actions_container_layout.addLayout(self.action_payload_layout)
        self.action_add_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_add_btn.setObjectName("action_add_btn")
        self.actions_container_layout.addWidget(self.action_add_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.actions_container_layout.addItem(spacerItem)
        self.action_button_layout = QtWidgets.QHBoxLayout()
        self.action_button_layout.setObjectName("action_button_layout")
        self.action_save_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_save_btn.setObjectName("action_save_btn")
        self.action_button_layout.addWidget(self.action_save_btn)
        self.action_run_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_run_btn.setObjectName("action_run_btn")
        self.action_button_layout.addWidget(self.action_run_btn)
        self.actions_container_layout.addLayout(self.action_button_layout)
        self.verticalLayout_3.addLayout(self.actions_container_layout)
        self.results_container = QtWidgets.QWidget(parent=self.actions_container)
        self.results_container.setObjectName("results_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.results_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.results_container_layout = QtWidgets.QVBoxLayout()
        self.results_container_layout.setContentsMargins(-1, -1, -1, 20)
        self.results_container_layout.setObjectName("results_container_layout")
        self.results_list_view = QtWidgets.QListView(parent=self.results_container)
        self.results_list_view.setObjectName("results_list_view")
        self.results_container_layout.addWidget(self.results_list_view)
        self.result_ok_btn = QtWidgets.QPushButton(parent=self.results_container)
        self.result_ok_btn.setObjectName("result_ok_btn")
        self.results_container_layout.addWidget(self.result_ok_btn)
        self.verticalLayout_2.addLayout(self.results_container_layout)
        self.verticalLayout_3.addWidget(self.results_container)
        self.container_layout.addWidget(self.actions_container)
        self.horizontalLayout_2.addLayout(self.container_layout)

        self.retranslateUi(PageFacebookRobot)
        QtCore.QMetaObject.connectSlotsByName(PageFacebookRobot)

    def retranslateUi(self, PageFacebookRobot):
        _translate = QtCore.QCoreApplication.translate
        PageFacebookRobot.setWindowTitle(_translate("PageFacebookRobot", "Form"))
        self.uid_container.setTitle(_translate("PageFacebookRobot", "UID"))
        self.username_container.setTitle(_translate("PageFacebookRobot", "Username"))
        self.note_container.setTitle(_translate("PageFacebookRobot", "Note"))
        self.type_container.setTitle(_translate("PageFacebookRobot", "Type"))
        self.groupt_container.setTitle(_translate("PageFacebookRobot", "Group"))
        self.name_container.setTitle(_translate("PageFacebookRobot", "Name"))
        self.filter_container_2.setTitle(_translate("PageFacebookRobot", "Filter"))
        self.action_add_btn.setText(_translate("PageFacebookRobot", "Add action"))
        self.action_save_btn.setText(_translate("PageFacebookRobot", "Save"))
        self.action_run_btn.setText(_translate("PageFacebookRobot", "Run"))
        self.result_ok_btn.setText(_translate("PageFacebookRobot", "Ok"))
