# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/my-manager.v2/ui/page_settings.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PageSettings(object):
    def setupUi(self, PageSettings):
        PageSettings.setObjectName("PageSettings")
        PageSettings.resize(910, 640)
        PageSettings.setStyleSheet("#PageSettings{\n"
"  font-family: \"Courier New\";\n"
"font-size: 13px;\n"
"  background-color: #FFFFFF;\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QCheckBox{\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(PageSettings)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PageSettings_layout = QtWidgets.QVBoxLayout()
        self.PageSettings_layout.setContentsMargins(-1, 0, -1, 0)
        self.PageSettings_layout.setSpacing(4)
        self.PageSettings_layout.setObjectName("PageSettings_layout")
        self.actions_container = QtWidgets.QGroupBox(parent=PageSettings)
        self.actions_container.setMaximumSize(QtCore.QSize(16777215, 80))
        self.actions_container.setObjectName("actions_container")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.actions_container)
        self.horizontalLayout_11.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.actions_container_layout = QtWidgets.QHBoxLayout()
        self.actions_container_layout.setObjectName("actions_container_layout")
        self.action_import_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_import_btn.setObjectName("action_import_btn")
        self.actions_container_layout.addWidget(self.action_import_btn)
        self.action_export_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_export_btn.setObjectName("action_export_btn")
        self.actions_container_layout.addWidget(self.action_export_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.actions_container_layout.addItem(spacerItem)
        self.horizontalLayout_11.addLayout(self.actions_container_layout)
        self.PageSettings_layout.addWidget(self.actions_container)
        self.setting_option = QtWidgets.QComboBox(parent=PageSettings)
        self.setting_option.setObjectName("setting_option")
        self.PageSettings_layout.addWidget(self.setting_option)
        self.setting_input = QtWidgets.QGroupBox(parent=PageSettings)
        self.setting_input.setObjectName("setting_input")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.setting_input)
        self.horizontalLayout_12.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.setting_input_layout = QtWidgets.QHBoxLayout()
        self.setting_input_layout.setObjectName("setting_input_layout")
        self.setting_value = QtWidgets.QLineEdit(parent=self.setting_input)
        self.setting_value.setObjectName("setting_value")
        self.setting_input_layout.addWidget(self.setting_value)
        self.setting_is_selected = QtWidgets.QCheckBox(parent=self.setting_input)
        self.setting_is_selected.setObjectName("setting_is_selected")
        self.setting_input_layout.addWidget(self.setting_is_selected)
        self.setting_save_btn = QtWidgets.QPushButton(parent=self.setting_input)
        self.setting_save_btn.setObjectName("setting_save_btn")
        self.setting_input_layout.addWidget(self.setting_save_btn)
        self.horizontalLayout_12.addLayout(self.setting_input_layout)
        self.PageSettings_layout.addWidget(self.setting_input)
        self.setting_table = QtWidgets.QTableView(parent=PageSettings)
        self.setting_table.setObjectName("setting_table")
        self.PageSettings_layout.addWidget(self.setting_table)
        self.horizontalLayout.addLayout(self.PageSettings_layout)

        self.retranslateUi(PageSettings)
        QtCore.QMetaObject.connectSlotsByName(PageSettings)

    def retranslateUi(self, PageSettings):
        _translate = QtCore.QCoreApplication.translate
        PageSettings.setWindowTitle(_translate("PageSettings", "Form"))
        self.actions_container.setTitle(_translate("PageSettings", "Actions"))
        self.action_import_btn.setText(_translate("PageSettings", "Import"))
        self.action_export_btn.setText(_translate("PageSettings", "Export"))
        self.setting_input.setTitle(_translate("PageSettings", "Add new profile container directory"))
        self.setting_value.setPlaceholderText(_translate("PageSettings", "Click to select profile container directory"))
        self.setting_is_selected.setText(_translate("PageSettings", "Set selected"))
        self.setting_save_btn.setText(_translate("PageSettings", "Save"))
