# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/my-manager.v2/ui/robot_action.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RobotAction(object):
    def setupUi(self, RobotAction):
        RobotAction.setObjectName("RobotAction")
        RobotAction.resize(480, 640)
        RobotAction.setStyleSheet("#RobotAction{\n"
"  font-family: \"Courier New\";\n"
"  background-color: #FFFFFF;\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"}\n"
"\n"
"QCheckBox{\n"
"  color: #212529;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(RobotAction)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FacebookAction_layout = QtWidgets.QVBoxLayout()
        self.FacebookAction_layout.setContentsMargins(-1, 0, -1, -1)
        self.FacebookAction_layout.setSpacing(4)
        self.FacebookAction_layout.setObjectName("FacebookAction_layout")
        self.main_container = QtWidgets.QGroupBox(parent=RobotAction)
        self.main_container.setTitle("")
        self.main_container.setObjectName("main_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_container)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_container_layout = QtWidgets.QHBoxLayout()
        self.main_container_layout.setObjectName("main_container_layout")
        self.action_name = QtWidgets.QComboBox(parent=self.main_container)
        self.action_name.setObjectName("action_name")
        self.main_container_layout.addWidget(self.action_name)
        self.action_option = QtWidgets.QComboBox(parent=self.main_container)
        self.action_option.setObjectName("action_option")
        self.main_container_layout.addWidget(self.action_option)
        self.action_payload = QtWidgets.QLineEdit(parent=self.main_container)
        self.action_payload.setObjectName("action_payload")
        self.main_container_layout.addWidget(self.action_payload)
        self.action_delete_btn = QtWidgets.QPushButton(parent=self.main_container)
        self.action_delete_btn.setObjectName("action_delete_btn")
        self.main_container_layout.addWidget(self.action_delete_btn)
        self.horizontalLayout_2.addLayout(self.main_container_layout)
        self.FacebookAction_layout.addWidget(self.main_container)
        self.group_url_container = QtWidgets.QGroupBox(parent=RobotAction)
        self.group_url_container.setObjectName("group_url_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_url_container)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.group_url_container_layout = QtWidgets.QVBoxLayout()
        self.group_url_container_layout.setSpacing(0)
        self.group_url_container_layout.setObjectName("group_url_container_layout")
        self.group_url_input = QtWidgets.QLineEdit(parent=self.group_url_container)
        self.group_url_input.setObjectName("group_url_input")
        self.group_url_container_layout.addWidget(self.group_url_input)
        self.verticalLayout_4.addLayout(self.group_url_container_layout)
        self.FacebookAction_layout.addWidget(self.group_url_container)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.FacebookAction_layout.addItem(spacerItem)
        self.content_container = QtWidgets.QGroupBox(parent=RobotAction)
        self.content_container.setTitle("")
        self.content_container.setObjectName("content_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_container)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_container_layout = QtWidgets.QVBoxLayout()
        self.content_container_layout.setContentsMargins(-1, 0, -1, 0)
        self.content_container_layout.setSpacing(4)
        self.content_container_layout.setObjectName("content_container_layout")
        self.product_image_btn = QtWidgets.QPushButton(parent=self.content_container)
        self.product_image_btn.setObjectName("product_image_btn")
        self.content_container_layout.addWidget(self.product_image_btn)
        self.product_images_list = QtWidgets.QListWidget(parent=self.content_container)
        self.product_images_list.setObjectName("product_images_list")
        self.content_container_layout.addWidget(self.product_images_list)
        self.product_title_input = QtWidgets.QLineEdit(parent=self.content_container)
        self.product_title_input.setObjectName("product_title_input")
        self.content_container_layout.addWidget(self.product_title_input)
        self.product_description_input = QtWidgets.QPlainTextEdit(parent=self.content_container)
        self.product_description_input.setObjectName("product_description_input")
        self.content_container_layout.addWidget(self.product_description_input)
        self.verticalLayout.addLayout(self.content_container_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.FacebookAction_layout.addWidget(self.content_container)
        self.verticalLayout_2.addLayout(self.FacebookAction_layout)

        self.retranslateUi(RobotAction)
        QtCore.QMetaObject.connectSlotsByName(RobotAction)

    def retranslateUi(self, RobotAction):
        _translate = QtCore.QCoreApplication.translate
        RobotAction.setWindowTitle(_translate("RobotAction", "Form"))
        self.action_delete_btn.setText(_translate("RobotAction", "Delete"))
        self.group_url_container.setTitle(_translate("RobotAction", "Group url"))
        self.product_image_btn.setText(_translate("RobotAction", "Open images"))
        self.product_title_input.setToolTip(_translate("RobotAction", "Title"))
        self.product_description_input.setToolTip(_translate("RobotAction", "Description"))
